export const leftOptions = [{
    label: "全国疫情分布",
    check: false,
    show: false,
}, {
    label: "鹿城区疫情分布",
    check: false,
    show: true,
    children: [{
        name: `隔离点`,
        unit: "处",
        id: "isolatedPoint",
        url: "http://172.20.89.7:6082/arcgis/rest/services/NewDataLuChengYiQinag/GeiLiDianLuCheng/MapServer",
        sublayers: "0",
        icon: "隔离点（红）",
        icon2: "隔离点（黄）",
        icon3: "隔离点（绿）",
        isLegend: true,
        check: false
    }, {
        name: `核酸采样点`,
        unit: "处",
        id: "detection",
        url: "http://172.20.89.7:6082/arcgis/rest/services/NewDataLuChengYiQinag/GeiLiDianLuCheng/MapServer",
        sublayers: "1",
        icon: "核酸检测点",
        isLegend: true,
        check: false
    }, {
        name: `入境隔离人员`,
        unit: "例",
        id: "quarantine",
        url: "http://172.20.89.7:6082/arcgis/rest/services/NewDataLuChengYiQinag/rujingshuju/MapServer",
        sublayers: "0",
        icon: "入境隔离人员",
        isLegend: true,
        check: false
    }]
}, {
    label: "网格管理",
    check: false,
    show: true,
    children: [{
        name: "街道",
        id: "street",
        isImg: true,
        isLegend: false,
        url: "http://172.20.89.7:6082/arcgis/rest/services/NewDataLuChengYiQinag/cs_grid/MapServer",
        sublayers: "0",
        check: true
    }, {
        name: "社区",
        id: "community",
        isLegend: false,
        url: "http://172.20.89.7:6082/arcgis/rest/services/NewDataLuChengYiQinag/cs_grid/MapServer",
        sublayers: "1",
        check: false
    }]
}]